### ISSUE TITLE
mariadb-server error

### ISSUE THREAD

**Issue by parruc** [jerob/docker-ispconfig#1]
I get this error during the build process:

<pre>
Errors were encountered while processing:
 /var/cache/apt/archives/mariadb-server-10.0_10.0.16-1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
2015/07/03 20:48:28 The command [/bin/sh -c apt-get -y install postfix postfix-mysql postfix-doc mariadb-client mariadb-server openssl getmail4 rkhunter binutils dovecot-imapd dovecot-pop3d dovecot-mysql dovecot-sieve dovecot-lmtpd sudo] returned a non-zero code: 100
</pre>

**Comment by parruc** [comment]
Updated docker to 1.7 and worked like a charm

**Comment by jerob** [comment]
Thanks for the comment. You can also pull an image from the docker hub : https://registry.hub.docker.com/u/jerob/docker-ispconfig/

docker pull jerob/docker-ispconfig
