### ISSUE TITLE
autoinstall.ini is missing some default values

### ISSUE THREAD

**Issue by eigood** [jerob/docker-ispconfig#10]
autoinstall.ini does not set some values that the install.php script prompts for.  The reason this wasn't detected, is that docker-build sets stdin = /dev/null, and install.php picks a sensible default.

Setting the values implicitly, however, makes this a bit easier to understand.

The options needed are:

mysql_port=3306
ispconfig_admin_password=admin

**Comment by jerob** [comment]
Thank you, done
