### ISSUE TITLE
18.04.2 LTS (Bionic Beaver) - Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use.

### ISSUE THREAD

**Issue by ricardotenv** [jerob/docker-ispconfig#23]
When I run the "docker run" command I get back the following error message:

Error response from daemon: driver failed programming external connectivity on endpoint ispconfig (b0b51609f81e996386cab780dc66595778d391d59f065469d7068162df5ceba9): Error starting userland proxy: listen tcp 0.0.0.0:53: bind: address already in use.

**Comment by kosztik** [comment]
You have a running bind. Try: /etc/init.d/bind stop

**Comment by ricardotenv** [comment]
> You have a running bind. Try: /etc/init.d/bind stop

return this to me:
-bash: /etc/init.d/bind: No such file or directory
or
-bash: /etc/init.d/bind9: No such file or directory

I believe this is because I do not have Bind installed.

**Comment by ricardotenv** [comment]
With netstat I identified the "systemd-resolved" using the port and ran the commands:

sudo systemctl stop systemd-resolved
sudo systemctl disable systemd-resolved

That solved the problem, but I believe it will bring future problems.

Everything about computer networks is very new to me.

**Comment by ricardotenv** [comment]
Add in /etc/resolve.cnf:

nameserver 8.8.8.8
nameserver 8.8.4.4

**Comment by wtt502** [comment]
> 使用netstat，我通过端口识别了“ systemd-resolved”并运行了以下命令：
> 
> sudo systemctl停止systemd解析
> sudo systemctl禁用systemd解析
> 
> 那解决了问题，但我相信它将带来未来的问题。
> 
> 对我而言，有关计算机网络的一切都是新事物。

出现了新问题,有遇到么?开启rabbitmq服务的时候超时
![image](https://user-images.githubusercontent.com/50694663/75842063-55c6d780-5e0a-11ea-8243-0df3ddefd10f.png)
