### ISSUE TITLE
/bin/systemctl doesn't remove .service suffix

### ISSUE THREAD

**Issue by eigood** [jerob/docker-ispconfig#6]
08.03.2017-17:30 - DEBUG - Restarting httpd: systemctl restart apache2.service
08.03.2017-17:30 - DEBUG - Apache restart return value is: 127
08.03.2017-17:30 - DEBUG - Apache online status after restart is: running
08.03.2017-17:30 - WARNING - Apache did not restart after the configuration change for website stanley.ispconfig. Reverting the configuration. Saved non-working config as /etc/apache2/sites-available/XXXX.vhost.err
08.03.2017-17:30 - WARNING - Reason for Apache restart failure: /bin/systemctl: line 4: /etc/init.d/apache2.service: No such file or directory
08.03.2017-17:30 - DEBUG - Calling function 'restartHttpd' from module 'web_module'.

**Comment by jerob** [comment]
That's true, done !
