### ISSUE TITLE
Remove all standalone instances of 'RUN service $service stop/start/restart"

### ISSUE THREAD

**Issue by eigood** [jerob/docker-ispconfig#8]
There are several instances of the following pattern in the Dockerfile:

"RUN service postfix restart"

During Dockerfile build, each and every RUN command starts a completely fresh container, does the RUN, then stops the container.  So the action of stop/start/restart only added additional layers, and slows down the build.

**Comment by jerob** [comment]
You're right, thanks for the advice. Done
