### ISSUE TITLE
Remove ntp/ntpdate in Dockerfile

### ISSUE THREAD

**Issue by eigood** [jerob/docker-ispconfig#9]
Containers started by docker have the same time./clock as the host, and the container can *not* change the time.  If the time is off, it must be fixed in the host.

See: http://stackoverflow.com/questions/24551592/how-to-make-sure-dockers-time-syncs-with-that-of-the-host

So, step 7 is somewhat pointless.

**Comment by jerob** [comment]
Thank you, done
